# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

# Create random tensor
rnd_t = torch.rand(7, 7)
rnd_t

tensor([[0.7752, 0.8016, 0.0996, 0.4550, 0.4358, 0.8236, 0.6429],
        [0.5668, 0.0030, 0.9951, 0.2939, 0.8123, 0.4243, 0.8637],
        [0.0776, 0.7989, 0.3928, 0.1881, 0.8853, 0.3359, 0.1396],
        [0.2307, 0.0895, 0.2847, 0.8198, 0.2251, 0.7609, 0.9425],
        [0.5066, 0.9203, 0.6891, 0.6373, 0.8387, 0.1366, 0.5521],
        [0.3127, 0.4265, 0.8293, 0.6479, 0.7051, 0.1028, 0.8284],
        [0.8450, 0.5835, 0.6807, 0.3740, 0.0433, 0.5730, 0.4949]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
rnd_t2 = torch.rand(1, 7)
# Perform matrix multiplication 
torch.mm(rnd_t, rnd_t2.T)

tensor([[2.0925],
        [1.5098],
        [0.7791],
        [1.7444],
        [1.5369],
        [1.3290],
        [1.8268]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
torch.manual_seed(0)
# Create two random tensors
rnd_t = torch.rand(7, 7)
rnd_t2 = torch.rand(1, 7)
# Matrix multiply tensors
torch.mm(rnd_t, rnd_t2.T), torch.mm(rnd_t, rnd_t2.T).size()

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [10]:
# Set random seed on the GPU
torch.cuda.manual_seed_all(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [18]:
# Set random seed
seed = torch.cuda.manual_seed(1234)

# Check for access to GPU
print(device)
# Create two random tensors on GPU
seed
t1 = torch.rand(2, 3)
seed
t2 = torch.rand(2, 3)
t1.to(device), t2.to(device)

cuda


(tensor([[0.0237, 0.4910, 0.1235],
         [0.1143, 0.4725, 0.5751]], device='cuda:0'),
 tensor([[0.2952, 0.7967, 0.1957],
         [0.9537, 0.8426, 0.0784]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [20]:
# Perform matmul on tensor_A and tensor_B
res = torch.mm(t1, t2.T)
res, torch.mm(t1, t2.T).size()

(tensor([[0.4223, 0.4460],
         [0.5227, 0.5522]]),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
res.max(), res.min()
# Find min



(tensor(0.5522), tensor(0.4223))

### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
res.argmax(), res.argmin()

# Find arg min


(tensor(3), tensor(0))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tt = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tt2 = torch.squeeze(tt)

# Print out tensors and their shapes
tt, tt.shape, tt2, tt2.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))