In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [4]:
scalar.ndim

0

In [5]:
# get tensor val
scalar.item()

8

In [6]:
# vector
vector = torch.tensor([8, 8])
vector

tensor([8, 8])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR

TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [17]:
### Random tensors
rand_tensor = torch.rand(3, 4)
rand_tensor

tensor([[0.8657, 0.0196, 0.5406, 0.1888],
        [0.6238, 0.5983, 0.9518, 0.7159],
        [0.5709, 0.8594, 0.2006, 0.2147]])

In [18]:
rand_tensor.ndim

2

In [19]:
# create rand tensor with simolar shape to an image tensor
rendom_image_size_tensor = torch.rand(size=(3, 224, 224)) #color channels, height, weight
rendom_image_size_tensor.shape, rendom_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [20]:
# zeros and ones

zero_tensor = torch.zeros(3, 4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zero_tensor*rand_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
# create range of tensors

one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
torch.arange(1, 11, 2)

tensor([1, 3, 5, 7, 9])

In [26]:
# creating tensors like (same shape)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors datatypes

In [27]:
# float32

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
# float 16

float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor.dtype

torch.float16

In [31]:
mult = float_32_tensor * float_16_tensor
mult

tensor([ 9., 36., 81.])

In [32]:
mult.dtype

torch.float32

### Getting info from tensors using attributes

.dtype, .shape, .device

### Manipulating tensors

In [33]:
tens1 = torch.tensor([1, 2, 3])
tens1 + 10

tensor([11, 12, 13])

In [34]:
tens1 * 10

tensor([10, 20, 30])

In [35]:
tens1 - 10

tensor([-9, -8, -7])

In [36]:
# pytorch functions

torch.mul(tens1, 11)

tensor([11, 22, 33])

In [37]:
tens1 / 123

tensor([0.0081, 0.0163, 0.0244])

In [38]:
# element-wise

print(tens1 * tens1)

# matrix multiplication (dot product) - inner demensions of matrices should match!
# resulting shape will be outer dimensions!

torch.matmul(tens1, tens1) #alias torch.mm

tensor([1, 4, 9])


tensor(14)

#### We can use tensor.T to transpose matrices in case of size mismatch

#### Finding min, max, etc

In [39]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
torch.min(x), min(x)

(tensor(0), tensor(0))

In [41]:
torch.max(x), max(x)

(tensor(90), tensor(90))

In [42]:
#torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [43]:
# float32 dtype required for mean

torch.mean(x.type(torch.float32))

tensor(45.)

In [44]:
x.type(torch.float32).mean()

tensor(45.)

In [45]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

#### Finding positional min and max - argmin, argmax

In [46]:
x.argmax() #index of position of max value

tensor(9)

In [47]:
x.argmin()

tensor(0)

### Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`torch.Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. | 
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. | 

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make the right elements of your tensors are mixing with the right elements of other tensors. 

Let's try them out.

First, we'll create a tensor.

In [48]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [49]:
# add extra dimension

x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [50]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [51]:
# change view

z = x.view(1, 9) # changes x because of the same memory shared
z, x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [52]:
# stack tensors on top of each other

x_stack = torch.stack([x, x, x, x], dim=0)
x_stack

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [53]:
x_stack = torch.stack([x, x, x, x], dim=1)
x_stack

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [54]:
x.squeeze() # removes all single dimensions

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [55]:
x.unsqueeze(dim=0), x.unsqueeze(dim=1)

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [56]:
# permute dimensions

x_orig = torch.rand(244, 244, 3)
x_permuted = x_orig.permute(2, 0, 1)
x_orig.shape, x_permuted.shape

(torch.Size([244, 244, 3]), torch.Size([3, 244, 244]))

#### Indexing (selecting data from tensors)

In [57]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [58]:
x[0] # index 0 dim

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
# index middle bracket
x[0][0] 

tensor([1, 2, 3])

In [60]:
# 0 elem
x[0][0][0]

tensor(1)

In [61]:
x[0][1][1]

tensor(5)

In [62]:
x[:, 0] # all of target dim

tensor([[1, 2, 3]])

In [63]:
x[:, 1, 1] 

tensor([5])

In [64]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

#### PyTorch and numpy

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.  

The two main methods you'll want to use for NumPy to PyTorch (and back again) are: 
* [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html) - NumPy array -> PyTorch tensor. 
* [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html) - PyTorch tensor -> NumPy array.


In [65]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

#### Setup device agnostic code

In [68]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'